# Generated by Django 4.1.7 on 2023-03-24 13:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=200)),
                ('LastName', models.CharField(max_length=200)),
                ('Profilepicture', models.ImageField(blank=True, default='user_pic/no-img.jpg', null=True, upload_to='profile/')),
                ('EmailAddress', models.EmailField(max_length=255, unique=True)),
                ('PhoneNumber', models.IntegerField()),
                ('RoomNumber', models.IntegerField()),
                ('Subjectstaught', models.CharField(default=5, max_length=200, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
