# Generated by Django 4.1.7 on 2023-03-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Subjectstaught',
            field=models.CharField(choices=[('Mathematics', 'Mathematics'), ('Computer science', 'Computer science'), ('Physics', 'Physics'), ('History', 'History'), ('geography', 'geography'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Arabic', 'Arabic')], max_length=200),
        ),
    ]
