# Generated by Django 4.1.7 on 2023-03-25 02:40

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0002_alter_teacher_subjectstaught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Subjectstaught',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mathematics', 'Mathematics'), ('Computer science', 'Computer science'), ('Physics', 'Physics'), ('History', 'History'), ('geography', 'geography'), ('Biology', 'Biology'), ('Chemistry', 'Chemistry'), ('English', 'English'), ('Arabic', 'Arabic')], max_length=100),
        ),
    ]
