# Generated by Django 4.1.7 on 2023-03-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryapp', '0003_alter_teacher_subjectstaught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='RoomNumber',
            field=models.CharField(max_length=100),
        ),
    ]
